# Generated by Django 4.0.5 on 2022-08-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_choice_question_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
        ),
    ]
