# Generated by Django 4.0.5 on 2022-08-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_remove_choice_lesson_remove_question_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='course',
            field=models.ForeignKey(default='online course', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
    ]
