# Generated by Django 4.0.5 on 2022-08-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_alter_choice_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='course',
            field=models.ForeignKey(default='online course', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
    ]
