# Generated by Django 4.0.5 on 2022-08-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_alter_choice_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='option',
        ),
    ]
