# Generated by Django 4.0.5 on 2022-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0009_remove_choice_is_correct_remove_choice_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.CharField(default='None of the above', max_length=200),
        ),
    ]
